source 'https://rubygems.org'
gem 'crypt'
gem 'json'
gem 'inline'

gem 'irb-benchmark'
gem 'RubyInline'

gem 'ruby-progressbar'
gem 'thread_safe'
gem 'ffi'
gem 'stackprof'
gem 'sysinfo'
gem 'sys-filesystem'



gem 'ferret'

gem 'fastimage'

