#!/bin/bash
# BareMetal Networks Emergence installer
dir="/etc/emergence"

echo "BareMetal Networks: Emergence"
echo "Beginning install..."
echo "Creating 'emergence' user..."
useradd -s /bin/bash -m -d /etc/emergence emergence

echo "Creating directory: $dir"
if [ -d $dir ]
then
	echo "Directory exists."
else
	mkdir $dir
fi

echo "Copying files..."
cp ../* $dir


echo "Setting up init.d..."
cp init.d /etc/init.d/emergence
chmod u+x /etc/init.d/emergence

#echo "Initializing crypto..."
#ruby $dir/default_configs.rb

echo "Copying Tests..."
cp -R ../tests $dir

echo "Testing..."
cd $dir
if ( ruby tests/test_libredox.rb &&
	ruby tests/test_libinstance.rb &&
	ruby tests/test_libem.rb )
then
	echo "Tests passed."
else
	echo "Tests failed. Please check to make sure all dependencies are installed."
	exit 1
fi

echo "Setting permissions..."
chown emergence:emergence $dir/tests
chown -R emergence:emergence $dir/*
chown root:root $dir/sniffer.rb
echo "Finished. Start with '/etc/init.d/emergence start'"
exit 0
