source 'https://rubygems.org'

gem 'rails', '4.0.0'	#'3.2.6'
gem 'railties', '4.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
gem 'mysql2'
gem 'rack'
  gem 'sass-rails'#,   '~> 3.2.3'
  gem 'coffee-rails'#, '~> 3.2.1'
  gem 'execjs'
  gem 'therubyracer'
#gem 'nodejs'
#  gem 'mysql',	'~> 2.8.1'
  gem 'will_paginate', '~> 3.0'
  #gem 'mysql2' #,	'~> 0.3.11'
#  gem 'iconv'
 # gem 'rmagick', '2.13.2'

#  gem 'galetahub-simple_captcha', :require => 'simple_captcha'
 # gem 'simple_captcha', :git => 'git://github.com/Azdaroth/simple-captcha.git'
      #  :branch => 'rails-4', :require => 'simple_captcha'
  #gem 'thin'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier'#, '>= 1.0.3'

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
 #gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
