# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e287100b34ea34f4278962a99c606cae34093414673cba66de9ece6138a3e9ab068488ee5569a597098700ac31c9a79a6ed6bb25a3c5127e4156499f95c046bc

test:
  secret_key_base: fd0d74cf0fd93f93ed05ae50110ba664bb502f7f9187db2f0093c59cae39f8bdc21707a4ecc1246798980a06095ddb6308a92f9ae9da81796f577a0646458538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
