# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

task :default => [:setup]
task :setup do
 sh 'date'
end

namespace :db do
task :railstask => :environment do
  # foo = ActiveREcord::Base.configurations
  # ActiveRecord::Base.establish_connections(foo[RAILS_ENV])
  # ActiveRecord::Base.connection.recreate_Database(ActiveREcord::Base.connection.current_database)
end
end
q