source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
gem 'bootstrap-sass', '~> 3.3.6'

gem 'font-awesome-sass', "~> 4.5.0"
#gem 'font-awesome-rails', '~> 4.3.0'
#em 'adminlte2-rails'
gem 'bson'
#gem 'bson_ext'

gem 'jquery-datatables-rails'
gem 'ajax-datatables-rails'
#gem 'sqlite3'
gem 'connection_pool'
gem 'redis'
gem 'redis-objects'
gem 'redis-namespace'
gem 'redis-rails'
gem 'redis-rack-cache'
gem 'msgpack_rails'
gem 'mongo'
gem 'mongoid', '~> 5.0.0'


# for sidekiq webui
gem 'sinatra'
gem 'slim'
gem 'sidekiq'

gem 'will_paginate', '~> 3.0.7'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby



# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
#gem 'thin'
#gem 'thin_service'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

## files that end in .md get rendered as markdown
## still need matching route like get ':action', :controller => :home to route
## /about to home#about
gem 'markdown-rails'
## Static pages, place them in pages/

gem 'high_voltage'


gem 'sinatra'
gem 'slim'
## User interface
#gem 'activeadmin'
gem 'rails-admin'
gem 'chartjs-ror'

#gem 'symmetric_encryption'
gem 'ransack'

# Use ActiveModel has_secure_password
 gem 'bcrypt', '~> 3.1.7'
gem 'symmetric-encryption'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'better_errors'
  gem 'byebug'
  gem 'quiet_assets'
 # gem 'foreman'
  gem 'rack-mini-profiler'
 # gem 'bullet'
  gem 'meta_request'
  #gem 'railroady'
  #gem 'dotenv-rails'
  # becuz my unit doesnt need testing, its always in production
  gem 'rspec-rails'
  gem 'pry'
  gem 'shoulda-matchers'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  gem 'rspec-sidekiq'
  gem "factory_girl_rails", ">= 1.6.0"
  gem "cucumber-rails", ">= 1.2.1"
  gem "capybara", ">= 1.1.2"
 # gem "database_cleaner"
 # gem "launchy"
 # gem 'guard'

end



gem 'devise'
